version: '3.4'

services:
  dockercomposedemoo:
    image: ${DOCKER_REGISTRY-}dockercomposedemo
    build:
      context: .
      dockerfile: DockerComposeDemo/Dockerfile
   
  redis:
   container_name: redis
   image: redis
   ports:
      # 端口映射
      - 6379:6379

  nginx:
   container_name: nginx
   image: nginx
   ports:
      # 端口映射
      - 8081:80
   volumes:
      - /Users/fenghui/projects/nginx/nginx.conf:/etc/nginx/nginx.conf 
